export const env = {
  REVALIDATE_SECRET: process.env.REVALIDATE_SECRET ?? "",
  MONGODB_URI: process.env.MONGODB_URI ?? "",
  ADMIN_API_KEY: process.env.ADMIN_API_KEY ?? "",
  ADMIN_SESSION_TTL_SECONDS: Number(process.env.ADMIN_SESSION_TTL_SECONDS ?? "86400"),
  ADMIN_INVITE_EXPIRES_HOURS: Number(process.env.ADMIN_INVITE_EXPIRES_HOURS ?? "72"),
  APP_URL: process.env.APP_URL ?? "http://localhost:3000",
  NODE_ENV: process.env.NODE_ENV ?? "development",
  SCREENSHOT_PROVIDER_URL: process.env.SCREENSHOT_PROVIDER_URL ?? "",
  SCREENSHOT_API_KEY: process.env.SCREENSHOT_API_KEY ?? "",
  PREVIEW_USE_STORAGE: process.env.PREVIEW_USE_STORAGE ?? "none",
  R2_ACCOUNT_ID: process.env.R2_ACCOUNT_ID ?? "",
  R2_ACCESS_KEY_ID: process.env.R2_ACCESS_KEY_ID ?? "",
  R2_SECRET_ACCESS_KEY: process.env.R2_SECRET_ACCESS_KEY ?? "",
  R2_BUCKET: process.env.R2_BUCKET ?? "",
  R2_ENDPOINT: process.env.R2_ENDPOINT ?? "",
  R2_REGION: process.env.R2_REGION ?? "auto",
  R2_FORCE_PATH_STYLE: process.env.R2_FORCE_PATH_STYLE ?? "true",
  R2_PUBLIC_BASE_URL: process.env.R2_PUBLIC_BASE_URL ?? process.env.R2_PUBLIC_BASE ?? "",
};
